
GAME_NAME = "Ecosystem simulation"

TILE_IMAGE_PATH = r"images/tilesheet.png"
SHEEP_IMAGE_PATH = r"images/PasturingSheepIdleSide.png"
WOLF_IMAGE_PATH = r"images/TimberWolfIdleSide.png"
GRASS_IMAGE_PATH = r"images/Grass.png"

FPS = 30

BACKGROUND = (255, 255, 255)

WINDOW_MOVING_SPEED = 20

TILE_SIZE = 64

SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900

TIME_INTERVAL = 5

MAP_WIDTH = 60 * TILE_SIZE
MAP_HEIGHT = 50 * TILE_SIZE

ANIMATION_FRAME_DURATION = 300

# Default creature property
HUNGER_LEVEL = 100
HUNGER_SPEED = 2
MATING_DESIRE_LEVEL = 0
MATING_DESIRE_SPEED = 5
MATING_DESIRE_THRESHOLD = 100
SPEED = 2
DETECTION_RANGE = 100
INTERACTIVE_RANGE = 30
TOWARD_FOOD_SPEED = 3
FOOD_AMOUNT = 60

# Default sheep property