
GAME_NAME = "Ecosystem simulation"

MONKEY_IMAGE_PATH = r"images/CuriousMonkeyIdleSide.png"
WOLF_IMAGE_PATH = r"images/TimberWolfIdleSide.png"

FPS = 30

BACKGROUND = (255, 255, 255)


WINDOW_MOVING_SPEED = 20

TILE_SIZE = 32

SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900

TIME_INTERVAL = 5

MAP_WIDTH = 50 * TILE_SIZE
MAP_HEIGHT = 50 * TILE_SIZE